### ISSUE TITLE
Theme broken

### ISSUE THREAD

**Issue by tamis-laan** [bardisty/gruvbox-rofi#4]
After updating Rofi the theme is broken, the text turned black and the highlighting is gone.

Running Rofi version 1.7.0

**Comment by DaveDavenport** [comment]
With the removal of a lot of deprecated option and glue code to make old deprecated options work some themes are broken.

On the rofi github dicussion page there are several quick fixes mentioned. 

I think adding something like this ( effect of a change from 1.6.1)  fixes the text colour:
```css
element-text, element-icon {
    background-color: inherit;
    text-color:       inherit;
}
```
